name: Import Doxygen Docs
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
       - name: Upload
         uses: actions/checkout@v2
       - name: Make Docs
         uses: mattnotmitt/doxygen-action@v1.9.2
       - uses: actions/upload-artifact@v3
         with:
               name: my-artifact
               path: path/to/artifact/world.txt
