name: Import Doxygen Docs
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
       - name: Upload–≤
         uses: actions/checkout@v2
       - name: Make Docs
         uses: mattnotmitt/doxygen-action@v1.9.2
       - uses: actions/upload-artifact@v3
         with:
               name: Docs
               path: ./docs
       - name: Push to another repository
         uses: cpina/github-action-push-to-another-repository@main
         env:
           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
         with:
           source-directory: 'docs'
           destination-github-username: 'NikitaKurguzov'
           destination-repository-name: 'labs.io'
           user-email: 2020100197@pnu.edu.ru
           target-branch: main
